services:
  ubuntu22.04:
    profiles: [verify]
    build:
      context: ..
      dockerfile: airgap-docker/Dockerfile.ubuntu22.04
      network: none
    network_mode: none
  node20-alpine:
    profiles: [verify]
    build:
      context: ..
      dockerfile: airgap-docker/Dockerfile.node20-alpine
      network: none
    network_mode: none
