storage: /verdaccio/storage

web:
  title: Local npm Registry
  gravatar: false

auth:
  htpasswd:
    file: /verdaccio/storage/htpasswd

uplinks: {}

publish:
  allow_offline: true

packages:
  "@*/*":
    access: $all
    publish: $all
    unpublish: $all
  "**":
    access: $all
    publish: $all
    unpublish: $all

server:
  keepAliveTimeout: 60

log: { type: stdout, format: pretty, level: http }
