server {
  listen 80;
  server_name _;
  client_max_body_size 100M;

  proxy_set_header Host $host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;
  resolver 127.0.0.11 valid=30s ipv6=off;
  set $api_upstream dify-api:5001;
  set $web_upstream dify-web:3000;
  set $plugin_daemon_upstream dify-plugin-daemon:5002;

  location /console/api {
    proxy_pass http://$api_upstream;
  }

  location /api {
    proxy_pass http://$api_upstream;
  }

  location /v1 {
    proxy_pass http://$api_upstream;
  }

  location /openapi {
    proxy_pass http://$api_upstream;
  }

  location /files {
    proxy_pass http://$api_upstream;
  }

  location /mcp {
    proxy_pass http://$api_upstream;
  }

  location /triggers {
    proxy_pass http://$api_upstream;
  }

  location /e/ {
    proxy_set_header Dify-Hook-Url $scheme://$host$request_uri;
    proxy_pass http://$plugin_daemon_upstream;
  }

  location /socket.io/ {
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_pass http://$api_upstream;
  }

  location / {
    proxy_pass http://$web_upstream;
  }
}
