name: ${STACK_NAME:-inferlab}

include:
  - ./00-common/docker-compose.yml
  - ./01-infra/docker-compose.yml
  - ./10-inference/docker-compose.yml
  - ./11-webui/docker-compose.yml
  - ./12-storage/docker-compose.yml
  - ./13-automation/docker-compose.yml
  - ./20-team-chat/docker-compose.yml
  - ./21-team-project/docker-compose.yml
  - ./22-team-wiki/docker-compose.yml
  - ./30-developer/docker-compose.yml
  - ./51-llmops/docker-compose.yml

networks:
  internal-nw:
