name: alfa-llm

include:
  - ./docker-compose.common.yml
  - ./docker-compose.inference.yml
  - ./docker-compose.openwebui.yml
  - ./docker-compose.comfyui.yml
  - ./docker-compose.carbone.yml
  - ./docker-compose.dify.yml
  - ./docker-compose.langfuse.yml
  - ./docker-compose.pagerless.yml
  - ./docker-compose.deepwiki.yml
