services:
  cloudflare:
    image: docker.io/cloudflare/cloudflared:latest
    container_name: cloudflare
    restart: unless-stopped
    profiles:
      - cloudflare
    command:
      - tunnel
      - --no-autoupdate
      - run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN:-}
