services:
  couchdb:
    image: docker.io/library/couchdb:latest
    container_name: couchdb
    profiles:
      - obsidian
    environment:
      - COUCHDB_USER=${COUCHDB_USER:-obsidian}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD:-sk-obsidian-db-key}
    volumes:
      - couchdb_data:/opt/couchdb/data
      - ./couchdb/local.ini:/opt/couchdb/etc/local.ini
    ports:
      - 5984:5984
    restart: always

volumes:
  couchdb_data:
