FROM docker.io/library/debian:13-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends aptly ca-certificates gnupg \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /aptly

RUN printf '{\n  "rootDir": "/aptly"\n}\n' > /etc/aptly.conf

ENV HOME=/aptly

WORKDIR /aptly
