general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY

litellm_settings:
  callbacks:
    - prometheus
    - langfuse_otel
  drop_params: true
  request_timeout: 600

router_settings:
  routing_strategy: simple-shuffle
  num_retries: 3

model_list:
  ### Ollama
  - model_name: google/gemma4:31b
    litellm_params:
      model: ollama/gemma4:31b-cloud
      api_base: http://ollama:11434
  - model_name: openai/gpt-oss:20b
    litellm_params:
      model: ollama/gpt-oss:20b-cloud
      api_base: http://ollama:11434
  - model_name: nvidia/nemotron-3-nano:30b
    litellm_params:
      model: ollama/nemotron-3-nano:30b-cloud
      api_base: http://ollama:11434

  ### OpenRouter
  - model_name: google/gemma4:31b
    litellm_params:
      model: openrouter/google/gemma-4-31b-it:free
      api_key: os.environ/OPENROUTER_API_KEY
  - model_name: openai/gpt-oss:20b
    litellm_params:
      model: openrouter/openai/gpt-oss-20b:free
      api_key: os.environ/OPENROUTER_API_KEY
  - model_name: nvidia/nemotron-3-nano:30b
    litellm_params:
      model: openrouter/nvidia/nemotron-3-nano-30b-a3b:free
      api_key: os.environ/OPENROUTER_API_KEY

  ### Google AI Studio
  - model_name: google/gemma4:31b
    litellm_params:
      model: gemini/gemma-4-31b-it
      api_key: os.environ/GEMINI_API_KEY

  ### Groq Cloud
  - model_name: openai/gpt-oss:20b
    litellm_params:
      model: groq/openai/gpt-oss-20b
      api_key: os.environ/GROQ_API_KEY

  ### Cloudflare Workers AI
  - model_name: openai/gpt-oss:20b
    litellm_params:
      model: cloudflare/@cf/openai/gpt-oss-20b
      api_key: os.environ/CLOUDFLARE_API_KEY

  ### TEI; HuggingFace Text Embedding Inference
  - model_name: cl-nagoya/ruri-v3:310m
    litellm_params:
      model: openai/cl-nagoya/ruri-v3-310m
      api_base: http://tei-embedding:8000/v1
      api_key: EMPTY
      encoding_format: float
      max_parallel_requests: 1
  - model_name: cl-nagoya/ruri-v3-reranker:310m
    litellm_params:
      model: huggingface/cl-nagoya/ruri-v3-reranker-310m
      api_base: http://tei-reranking:8000
      api_key: EMPTY
      encoding_format: float
      max_parallel_requests: 1

  ### TTS
  - model_name: kokoro
    litellm_params:
      model: openai/kokoro
      api_base: http://kokoro:8880/v1
      api_key: not-needed
    model_info:
      mode: audio_speech
