general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
  session_id_header_name: X-OpenWebUI-Chat-Id
  user_header_mappings:
    - header_name: X-OpenWebUI-User-Id
      litellm_user_role: internal_user
    - header_name: X-OpenWebUI-User-Email
      litellm_user_role: customer

litellm_settings:
  callbacks:
    - langfuse_otel
  drop_params: true
  request_timeout: 600

model_list:
  ### Ollama
  - model_name: ollama/google/gemma4:31b-cloud
    litellm_params:
      model: ollama_chat/gemma4:31b-cloud
      api_base: http://ollama:11434
  - model_name: ollama/openai/gpt-oss:20b-cloud
    litellm_params:
      model: ollama_chat/gpt-oss:20b-cloud
      api_base: http://ollama:11434
  - model_name: ollama/nvidia/nemotron-3-nano:30b-cloud
    litellm_params:
      model: ollama_chat/nemotron-3-nano:30b-cloud
      api_base: http://ollama:11434

  ### OpenRouter
  - model_name: openrouter/google/gemma-4-31b-it:free
    litellm_params:
      model: openrouter/google/gemma-4-31b-it:free
      api_key: os.environ/OPENROUTER_API_KEY
  - model_name: openrouter/nvidia/nemotron-3-ultra-550b-a55b:free
    litellm_params:
      model: openrouter/nvidia/nemotron-3-ultra-550b-a55b:free
      api_key: os.environ/OPENROUTER_API_KEY
  - model_name: openrouter/openrouter/free-router
    litellm_params:
      model: openrouter/openrouter/free
      api_key: os.environ/OPENROUTER_API_KEY

  ### Google AI Studio
  - model_name: google/gemma-4-31b-it
    litellm_params:
      model: gemini/gemma-4-31b-it
      api_key: os.environ/GEMINI_API_KEY
  - model_name: google/gemini-3.5-flash
    litellm_params:
      model: gemini/gemini-3.5-flash
      api_key: os.environ/GEMINI_API_KEY
  - model_name: google/gemini-embedding-2
    litellm_params:
      model: gemini/gemini-embedding-2
      api_key: os.environ/GEMINI_API_KEY

  ### TEI; HuggingFace Text Embedding Inference
  - model_name: huggingface/cl-nagoya/ruri-v3:310m
    litellm_params:
      model: openai/ruri-v3:310m
      api_base: http://tei-embedding:8000/v1
      api_key: EMPTY
      encoding_format: float
  - model_name: huggingface/cl-nagoya/ruri-v3-reranker:310m
    litellm_params:
      model: huggingface/cl-nagoya/ruri-v3-reranker-310m
      api_base: http://tei-reranking:8000
      api_key: EMPTY
      encoding_format: float

  # TTS
  - model_name: voicevox/voicevox-tts
    litellm_params:
      model: openai/tts-1
      api_base: http://voicevox-openai-tts:8000/v1
      api_key: EMPTY
    model_info:
      mode: audio_speech

  ### vLLM
  # - model_name: thinking-model
  #   litellm_params:
  #     model: openai/Qwen3.6-27B-FP8:27B
  #     api_base: http://vllm-foundation:8000/v1
  #     api_key: EMPTY
  #     extra_body:
  #       chat_template_kwargs:
  #         enable_thinking: false
  #   model_info:
  #     max_input_tokens: 28672
  #     max_output_tokens: 4096
  #     supports_function_calling: true
  #     supports_parallel_function_calling: false
  # - model_name: instruct-model
  #   litellm_params:
  #     model: openai/Qwen3.6-27B-FP8:27B
  #     api_base: http://vllm-foundation:8000/v1
  #     api_key: EMPTY
  #     extra_body:
  #       chat_template_kwargs:
  #         enable_thinking: false
  #   model_info:
  #     max_input_tokens: 28672
  #     max_output_tokens: 4096
  #     supports_function_calling: true
  #     supports_parallel_function_calling: false
  # - model_name: embedding-model
  #   litellm_params:
  #     model: openai/ruri-v3:310m
  #     api_base: http://vllm-embedding:8000/v1
  #     api_key: EMPTY
  #     encoding_format: float
  # - model_name: reranking-model
  #   litellm_params:
  #     model: openai/ruri-v3-reranker:310m
  #     api_base: http://vllm-reranking:8000/v1
  #     api_key: EMPTY
  #     encoding_format: float
