---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

# providers:
#   openweathermap: openweathermapapikey
#   weatherapi: weatherapiapikey

layout:
  - 00-common:
      icon: /icons/homepage.png
      style: row
      columns: 4
  - 01-infra:
      icon: /icons/cloudflared.png
      style: row
      columns: 4
  - 10-inference:
      icon: /icons/ollama.png
      style: row
      columns: 4
  - 11-webui:
      icon: /icons/open-webui.png
      style: row
      columns: 4
  - 12-storage:
      icon: /icons/nextcloud.png
      style: row
      columns: 4
  - 51-llmops:
      icon: /icons/grafana.png
      style: row
      columns: 4
