---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

# providers:
#   openweathermap: openweathermapapikey
#   weatherapi: weatherapiapikey

layout:
  - 00-common:
      icon: /icons/mdi-home.png
      style: row
      columns: 4
  - 01-pubnet:
      icon: /icons/mdi-cloud.png
      style: row
      columns: 4
  - 10-inference:
      icon: /icons/mdi-brain.png
      style: row
      columns: 4
  - 11-rag:
      icon: /icons/mdi-web.png
      style: row
      columns: 4
  - 12-registry:
      icon: /icons/mdi-warehouse.png
      style: row
      columns: 4
  - 20-owui:
      icon: /icons/mdi-web.png
      style: row
      columns: 4
  - 21-dify:
      icon: /icons/mdi-robot.png
      style: row
      columns: 4
  - 30-nextcloud:
      icon: /icons/mdi-nas.png
      style: row
      columns: 4
  - 31-bookstack:
      icon: /icons/mdi-book.png
      style: row
      columns: 4
  - 32-kaneo:
      icon: /icons/mdi-bulletin-board.png
      style: row
      columns: 4
  - 33-zulip:
      icon: /icons/mdi-chat.png
      style: row
      columns: 4
  - 34-gitea:
      icon: /icons/mdi-file-code.png
      style: row
      columns: 4
  - 39-leantime:
      icon: /icons/mdi-bulletin-board.png
      style: row
      columns: 4
  - 40-obsidian:
      icon: /icons/mdi-database.png
      style: row
      columns: 4
  - 50-o11y:
      icon: /icons/mdi-monitor-eye.png
      style: row
      columns: 4
  - 51-llmops:
      icon: /icons/mdi-monitor-shimmer.png
      style: row
      columns: 4
