---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

# providers:
#   openweathermap: openweathermapapikey
#   weatherapi: weatherapiapikey

layout:
  - 00-common:
      icon: /icons/homepage.png
      style: row
      columns: 4
  - 01-keycloak:
      icon: /icons/keycloak.png
      style: row
      columns: 4
  - 02-pubnet:
      icon: /icons/mdi-cloud.png
      style: row
      columns: 4
  - 10-inference:
      icon: /icons/litellm.png
      style: row
      columns: 4
  - 11-rag:
      icon: /icons/docling.png
      style: row
      columns: 4
  - 12-registry:
      icon: /icons/docker.png
      style: row
      columns: 4
  - 20-owui:
      icon: /icons/open-webui.png
      style: row
      columns: 4
  - 21-dify:
      icon: /icons/dify.png
      style: row
      columns: 4
  - 30-nextcloud:
      icon: /icons/nextcloud.png
      style: row
      columns: 4
  - 31-bookstack:
      icon: /icons/bookstack.png
      style: row
      columns: 4
  - 32-kaneo:
      icon: /icons/kaneo.png
      style: row
      columns: 4
  - 33-zulip:
      icon: /icons/zulip.png
      style: row
      columns: 4
  - 34-gitea:
      icon: /icons/gitea.png
      style: row
      columns: 4
  - 39-leantime:
      icon: /icons/leantime.png
      style: row
      columns: 4
  - 40-obsidian:
      icon: /icons/obsidian.png
      style: row
      columns: 4
  - 50-o11y:
      icon: /icons/grafana.png
      style: row
      columns: 4
  - 51-langfuse:
      icon: /icons/langfuse.png
      style: row
      columns: 4
