{
 "title": "CouchDB",
 "tags": [
  "o11y",
  "service",
  "couchdb"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Targets Up",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"couchdb\"})"
    }
   ]
  },
  {
   "title": "Target Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"couchdb\"})"
    }
   ]
  },
  {
   "title": "Scraped Samples",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(scrape_samples_scraped{job=\"couchdb\"})"
    }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "scrape_duration_seconds{job=\"couchdb\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Scrape Samples",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "scrape_samples_scraped{job=\"couchdb\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Target Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "up{job=\"couchdb\"}"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(couchdb_httpd_requests{job=\"couchdb\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Database Reads/Writes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(couchdb_database_reads{job=\"couchdb\"}[5m])",
     "legendFormat": "reads"
    },
    {
     "expr": "rate(couchdb_database_writes{job=\"couchdb\"}[5m])",
     "legendFormat": "writes"
    }
   ]
  },
  {
   "title": "Open Databases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "couchdb_open_databases{job=\"couchdb\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}