{
 "title": "Qdrant",
 "tags": [
  "o11y",
  "service",
  "qdrant"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Targets Up",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"qdrant\"})"
    }
   ]
  },
  {
   "title": "Target Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"qdrant\"})"
    }
   ]
  },
  {
   "title": "Scraped Samples",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(scrape_samples_scraped{job=\"qdrant\"})"
    }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "scrape_duration_seconds{job=\"qdrant\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Scrape Samples",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "scrape_samples_scraped{job=\"qdrant\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Target Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "up{job=\"qdrant\"}"
    }
   ]
  },
  {
   "title": "REST Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (method, status) (rate(rest_responses_total{job=\"qdrant\"}[5m]))",
     "legendFormat": "{{method}} {{status}}"
    }
   ]
  },
  {
   "title": "gRPC Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (method, status) (rate(grpc_responses_total{job=\"qdrant\"}[5m]))",
     "legendFormat": "{{method}} {{status}}"
    }
   ]
  },
  {
   "title": "App Info",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "app_info{job=\"qdrant\"}"
    }
   ]
  }
 ]
}