{
 "title": "RabbitMQ",
 "tags": [
  "o11y",
  "service",
  "rabbitmq"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Targets Up",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"rabbitmq\"})"
    }
   ]
  },
  {
   "title": "Target Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"rabbitmq\"})"
    }
   ]
  },
  {
   "title": "Scraped Samples",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(scrape_samples_scraped{job=\"rabbitmq\"})"
    }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "scrape_duration_seconds{job=\"rabbitmq\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Scrape Samples",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "scrape_samples_scraped{job=\"rabbitmq\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Target Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "up{job=\"rabbitmq\"}"
    }
   ]
  },
  {
   "title": "RabbitMQ Up",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rabbitmq_up{job=\"rabbitmq\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Queue Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (queue) (rabbitmq_queue_messages{job=\"rabbitmq\"})",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rabbitmq_connections{job=\"rabbitmq\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}