x-external-dns-stabilizer: &external-dns-stabilizer
  dns:
    - 1.1.1.1
    - 8.8.8.8
  dns_search:
    - .
  dns_opt:
    - "timeout:1"
    - "attempts:2"
    - "ndots:1"

services:
  cloudflare:
    <<: *external-dns-stabilizer
    image: docker.io/cloudflare/cloudflared:2026.8.2
    container_name: ${STACK_NAME}-cloudflare
    restart: unless-stopped
    profiles:
      - pubnet
    command:
      - tunnel
      - --no-autoupdate
      - --metrics
      - 0.0.0.0:20241
      - --protocol
      - http2
      - run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN:-}
    networks:
      - internal-nw
    healthcheck:
      test: [ "CMD", "cloudflared", "tunnel", "--metrics", "127.0.0.1:20241", "ready" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    labels:
      - homepage.icon=/icons/cloudflared.png
      - homepage.group=02-pubnet
      - homepage.name=Cloudflare
      - homepage.description=Secure outband tunnel

networks:
  internal-nw:
